apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: buildbarn
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: storage
        resources:
          requests:
            cpu: "1"
            memory: 8Gi
          limits:
            memory: 16Gi
