apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-ubuntu22-04
  namespace: buildbarn
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: scheduler
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
