apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-ubuntu22-04
  namespace: buildbarn
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: worker
        resources:
          requests:
            cpu: 500m
            memory: 4Gi
          limits:
            memory: 32Gi
      - name: runner
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            memory: 32Gi
      initContainers:
      - name: bb-runner-installer
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
      - name: volume-init
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
